package de.quinscape.exceed.model.domain;

import com.google.common.collect.ImmutableSet;
import de.quinscape.exceed.model.AutoVersionedModel;
import de.quinscape.exceed.model.TopLevelModel;
import de.quinscape.exceed.model.annotation.IncludeDocs;
import de.quinscape.exceed.runtime.application.RuntimeApplication;
import de.quinscape.exceed.runtime.domain.DomainService;
import de.quinscape.exceed.runtime.model.JSONFormat;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.svenson.JSONProperty;
import org.svenson.JSONTypeHint;

import javax.annotation.PostConstruct;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Represents an domain entity type within an exceed application.
 *
 * The persistent JSON output for this model generated by  {@link de.quinscape.exceed.runtime.model.ModelJSONServiceImpl#toJSON(RuntimeApplication, DomainType, JSONFormat)}.
 *
 */
public class DomainType
    extends TopLevelModel
    implements AutoVersionedModel
{
    private final static Logger log = LoggerFactory.getLogger(DomainType.class);

    public final static Set<String> RESERVED_NAMES = ImmutableSet.of(
        DomainProperty.DATA_LIST_PROPERTY_TYPE,
        DomainProperty.DATA_LIST_ROOT_PROPERTY_TYPE,
        DomainProperty.DOMAIN_TYPE_PROPERTY_TYPE
    );

    public final static String ID_PROPERTY = "id";

    /**
     * Storage used for internal data types.
     */
    public final static String SYSTEM_STORAGE = "systemStorage";

    /**
     * Default storage for non-system types
     */
    public final static String DEFAULT_STORAGE = "jooqDatabaseStorage";

    private List<String> pkFields = Collections.singletonList(ID_PROPERTY);

    private boolean system;

    private String version;

    private Set<String> pkFieldSet = new HashSet<>(pkFields);

    /**
     * the linked hash map type ensures our properties stay in definition order
     */
    private List<DomainProperty> properties;

    private DomainService domainService;

    private String storageConfiguration;

    private String identityGUID;


    @Override
    public void setName(String name)
    {
        if (RESERVED_NAMES.contains(name))
        {
            throw new IllegalArgumentException("'" + name + "' is a reserved domain object name.");
        }

        super.setName(name);
    }


    @JSONTypeHint(DomainProperty.class)
    public void setProperties(List<DomainProperty> properties)
    {
        this.properties = properties;
    }


    /**
     * List of properties for this domain type.
     *
     * @return
     */
    @IncludeDocs
    @JSONProperty(priority = -40)
    public List<DomainProperty> getProperties()
    {
        return properties;
    }


    public void setDomainService(DomainService domainService)
    {
        this.domainService = domainService;
    }


    public void setPkFields(List<String> pkFields)
    {
        if (pkFields == null)
        {
            throw new IllegalArgumentException("pkFields can't be null");
        }

        this.pkFields = pkFields;
        this.pkFieldSet = new HashSet<>(pkFields);
    }


    /**
     * List of properties that form the primary key for this type.
     */
    @JSONTypeHint(String.class)
    @JSONProperty(priority = -10)
    public List<String> getPkFields()
    {
        return pkFields;
    }


    /**
     * DomainService
     *
     * @return
     */
    @JSONProperty(ignore = true)
    public DomainService getDomainService()
    {
        return domainService;
    }


    public boolean isPKField(String name)
    {
        return pkFieldSet.contains(name);
    }


    @Override
    public String toString()
    {
        return super.toString() + ": "
            + "pkFields = " + pkFields
            + ", properties = " + properties
            ;
    }


    @PostConstruct
    public void init()
    {
        final String domainTypeName = getName();

        log.debug("Init {}", domainTypeName);

        for (DomainProperty property : properties)
        {
            property.setDomainType(domainTypeName);

            if (property.getName().equals(ID_PROPERTY))
            {
                property.setRequired(true);
            }

            if (property.getType().equals("UUID") && property.getMaxLength() <= 0)
            {
                property.setMaxLength(36);
            }
        }
    }


    @JSONProperty(value = "storage", ignoreIfNull = true, priority = -20)
    public String getStorageConfiguration()
    {
        return storageConfiguration;
    }


    public void setStorageConfiguration(String storageConfiguration)
    {
        this.storageConfiguration = storageConfiguration;
    }


    @JSONProperty(priority = -30)
    public boolean isSystem()
    {
        return system;
    }


    public void setSystem(boolean system)
    {
        this.system = system;
    }


    @Override
    @JSONProperty(priority = 10, ignoreIfNull = true)
    public String getVersionGUID()
    {
        return version;
    }


    @Override
    public void setVersionGUID(String version)
    {
        this.version = version;
    }


    @Override
    public String getIdentityGUID()
    {
        return identityGUID;
    }


    @Override
    @JSONProperty(priority = 20)
    public void setIdentityGUID(String identity)
    {
        this.identityGUID = identity;
    }
}
