/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables.records;


import de.quinscape.exceed.domain.tables.AppState;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppStateRecord extends UpdatableRecordImpl<AppStateRecord> implements Record7<String, String, String, Integer, String, String, String> {

	private static final long serialVersionUID = -594105937;

	/**
	 * Setter for <code>public.app_state.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.app_state.id</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.app_state.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.app_state.name</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.app_state.path</code>.
	 */
	public void setPath(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.app_state.path</code>.
	 */
	@NotNull
	@Size(max = 255)
	public String getPath() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.app_state.status</code>.
	 */
	public void setStatus(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.app_state.status</code>.
	 */
	@NotNull
	public Integer getStatus() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>public.app_state.extensions</code>.
	 */
	public void setExtensions(String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.app_state.extensions</code>.
	 */
	@Size(max = 255)
	public String getExtensions() {
		return (String) getValue(4);
	}

	/**
	 * Setter for <code>public.app_state.context</code>.
	 */
	public void setContext(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.app_state.context</code>.
	 */
	public String getContext() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.app_state.domain_version</code>.
	 */
	public void setDomainVersion(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.app_state.domain_version</code>.
	 */
	@Size(max = 36)
	public String getDomainVersion() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, Integer, String, String, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, Integer, String, String, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AppState.APP_STATE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AppState.APP_STATE.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AppState.APP_STATE.PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return AppState.APP_STATE.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return AppState.APP_STATE.EXTENSIONS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return AppState.APP_STATE.CONTEXT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return AppState.APP_STATE.DOMAIN_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getExtensions();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getContext();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getDomainVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord value3(String value) {
		setPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord value4(Integer value) {
		setStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord value5(String value) {
		setExtensions(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord value6(String value) {
		setContext(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord value7(String value) {
		setDomainVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppStateRecord values(String value1, String value2, String value3, Integer value4, String value5, String value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppStateRecord
	 */
	public AppStateRecord() {
		super(AppState.APP_STATE);
	}

	/**
	 * Create a detached, initialised AppStateRecord
	 */
	public AppStateRecord(String id, String name, String path, Integer status, String extensions, String context, String domainVersion) {
		super(AppState.APP_STATE);

		setValue(0, id);
		setValue(1, name);
		setValue(2, path);
		setValue(3, status);
		setValue(4, extensions);
		setValue(5, context);
		setValue(6, domainVersion);
	}
}
