/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables.records;


import de.quinscape.exceed.domain.tables.AppTranslation;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppTranslationRecord extends UpdatableRecordImpl<AppTranslationRecord> implements Record7<String, String, String, String, Timestamp, String, String> {

	private static final long serialVersionUID = -56495912;

	/**
	 * Setter for <code>public.app_translation.id</code>.
	 */
	public void setId(String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.app_translation.id</code>.
	 */
	@NotNull
	@Size(max = 36)
	public String getId() {
		return (String) getValue(0);
	}

	/**
	 * Setter for <code>public.app_translation.locale</code>.
	 */
	public void setLocale(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.app_translation.locale</code>.
	 */
	@NotNull
	@Size(max = 64)
	public String getLocale() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>public.app_translation.tag</code>.
	 */
	public void setTag(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.app_translation.tag</code>.
	 */
	@NotNull
	@Size(max = 255)
	public String getTag() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>public.app_translation.translation</code>.
	 */
	public void setTranslation(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.app_translation.translation</code>.
	 */
	@NotNull
	public String getTranslation() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>public.app_translation.created</code>.
	 */
	public void setCreated(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.app_translation.created</code>.
	 */
	@NotNull
	public Timestamp getCreated() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.app_translation.process_name</code>.
	 */
	public void setProcessName(String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.app_translation.process_name</code>.
	 */
	@Size(max = 64)
	public String getProcessName() {
		return (String) getValue(5);
	}

	/**
	 * Setter for <code>public.app_translation.view_name</code>.
	 */
	public void setViewName(String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.app_translation.view_name</code>.
	 */
	@Size(max = 64)
	public String getViewName() {
		return (String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<String> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, String, Timestamp, String, String> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<String, String, String, String, Timestamp, String, String> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field1() {
		return AppTranslation.APP_TRANSLATION.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return AppTranslation.APP_TRANSLATION.LOCALE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AppTranslation.APP_TRANSLATION.TAG;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return AppTranslation.APP_TRANSLATION.TRANSLATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return AppTranslation.APP_TRANSLATION.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field6() {
		return AppTranslation.APP_TRANSLATION.PROCESS_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field7() {
		return AppTranslation.APP_TRANSLATION.VIEW_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getLocale();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getTag();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTranslation();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value6() {
		return getProcessName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value7() {
		return getViewName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord value1(String value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord value2(String value) {
		setLocale(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord value3(String value) {
		setTag(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord value4(String value) {
		setTranslation(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord value5(Timestamp value) {
		setCreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord value6(String value) {
		setProcessName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord value7(String value) {
		setViewName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslationRecord values(String value1, String value2, String value3, String value4, Timestamp value5, String value6, String value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppTranslationRecord
	 */
	public AppTranslationRecord() {
		super(AppTranslation.APP_TRANSLATION);
	}

	/**
	 * Create a detached, initialised AppTranslationRecord
	 */
	public AppTranslationRecord(String id, String locale, String tag, String translation, Timestamp created, String processName, String viewName) {
		super(AppTranslation.APP_TRANSLATION);

		setValue(0, id);
		setValue(1, locale);
		setValue(2, tag);
		setValue(3, translation);
		setValue(4, created);
		setValue(5, processName);
		setValue(6, viewName);
	}
}
