/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public class ASTAdd
    extends OperatorNode
{
    public ASTAdd(int id)
    {
        super(id);
        setOperator(Operator.ADD);
    }


    public ASTAdd(ExpressionParser p, int id)
    {
        super(p, id);
        setOperator(Operator.ADD);

    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data)
    {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=f3a17b93ac0b057731434bf6c92f2b82 (do not edit this line) */
