/* Generated By:JJTree: Do not edit this line. ASTComputedPropertyChain.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public
class ASTComputedPropertyChain extends SimpleNode {
  public ASTComputedPropertyChain(int id) {
    super(id);
  }

  public ASTComputedPropertyChain(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=94ff93c262886853ce7d28fa7ba3a844 (do not edit this line) */
