/* Generated By:JJTree: Do not edit this line. ASTDiv.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public
class ASTDiv extends OperatorNode {
  public ASTDiv(int id) {
    super(id);
    setOperator(Operator.DIVIDE);
  }

  public ASTDiv(ExpressionParser p, int id) {
    super(p, id);
    setOperator(Operator.DIVIDE);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d96a26b434cac41c9c55cc3b55cc18ff (do not edit this line) */
