/* Generated By:JJTree: Do not edit this line. ASTExpressionSequence.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public
class ASTExpressionSequence extends SimpleNode {
  public ASTExpressionSequence(int id) {
    super(id);
  }

  public ASTExpressionSequence(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=80391e39137aebce3173c6ef52f4e911 (do not edit this line) */
