/* Generated By:JJTree: Do not edit this line. ASTFloat.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public
class ASTFloat extends SimpleNode {

  private double value;
  public ASTFloat(int id) {
    super(id);
  }

  public ASTFloat(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return visitor.visit(this, data);
  }

  @Override
  public String toString()
  {
    return super.toString() + " " + value;
  }

  public double getValue()
  {
    return value;
  }


  public void setValue(double value)
  {
    this.value = value;
  }
}
/* JavaCC - OriginalChecksum=4d4aec308e20f117b55393ed4839eb0a (do not edit this line) */
