/* Generated By:JJTree: Do not edit this line. ASTFunction.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public
class
    ASTFunction extends SimpleNode {

  private String name;
  public ASTFunction(int id) {
    super(id);
  }

  public ASTFunction(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return visitor.visit(this, data);
  }


  @Override
  public String toString()
  {
    return super.toString() + " " + name;
  }


  public String getName()
  {
    return name;
  }


  public void setName(String name)
  {
    this.name = name;
  }
}
/* JavaCC - OriginalChecksum=8946653b0bfaf254c46b9d523d6389d9 (do not edit this line) */
