/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;


public
class ASTIdentifier extends SimpleNode {

  private String name;

  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return visitor.visit(this, data);
  }

  @Override
  public String toString()
  {
    return super.toString() + " " + name;
  }

  public String getName()
  {
    return name;
  }


  public void setName(String name)
  {
    this.name = name;
  }
}
/* JavaCC - OriginalChecksum=9bbd2ea5eef854ef7e63ee9fcf0a7d87 (do not edit this line) */
