/* Generated By:JJTree: Do not edit this line. ASTLogicalOr.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public
class ASTLogicalOr extends SimpleNode {
  public ASTLogicalOr(int id) {
    super(id);
  }

  public ASTLogicalOr(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=049d7041bfaaf2b894efad7273d6b7f0 (do not edit this line) */
