/* Generated By:JJTree: Do not edit this line. ASTPropertyChainSquare.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public class ASTPropertyChainSquare
    extends SimpleNode
    implements PropertyChainLink
{
    public ASTPropertyChainSquare(int id)
    {
        super(id);
    }


    public ASTPropertyChainSquare(ExpressionParser p, int id)
    {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data)
    {

        return
            visitor.visit(this, data);
    }

    public String toString()
    {
        return super.toString() + " " + jjtGetChild(0).toString();
    }

}
/* JavaCC - OriginalChecksum=1f3c937c846489bddfcbbfe393f9bbff (do not edit this line) */
