/* Generated By:JJTree: Do not edit this line. ASTString.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,
NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

import de.quinscape.exceed.model.domain.PropertyModel;
import de.quinscape.exceed.runtime.util.ExpressionUtil;

public class ASTString
    extends SimpleNode
    implements LiteralValueNode
{

    private String value;


    public ASTString(int id)
    {
        super(id);
    }


    public ASTString(ExpressionParser p, int id)
    {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(ExpressionParserVisitor visitor, Object data)
    {

        return visitor.visit(this, data);
    }


    @Override
    public String toString()
    {
        return super.toString() + " " + value;
    }


    public String getValue()
    {
        return value;
    }


    public void setValue(String value)
    {
        this.value = value;
    }


    @Override
    public Object getLiteralValue()
    {
        return value;
    }


    @Override
    public PropertyModel getLiteralType()
    {
        return ExpressionUtil.PLAINTEXT_TYPE;
    }
}
/* JavaCC - OriginalChecksum=7061d8b76429e006ee56f1902d8505b5 (do not edit this line) */
