/* Generated By:JJTree: Do not edit this line. ASTSub.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package de.quinscape.exceed.expression;

public
class ASTSub extends OperatorNode {
  public ASTSub(int id) {
    super(id);
    setOperator(Operator.SUBTRACT);
  }

  public ASTSub(ExpressionParser p, int id) {
    super(p, id);
    setOperator(Operator.SUBTRACT);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b15455db1c37325c0635a4728b9c17d3 (do not edit this line) */
