/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 6.0_1 */
package de.quinscape.exceed.expression;

public interface ExpressionParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTLOGICALOR = 2;
  public int JJTLOGICALAND = 3;
  public int JJTEQUALITY = 4;
  public int JJTRELATIONAL = 5;
  public int JJTADD = 6;
  public int JJTSUB = 7;
  public int JJTMULT = 8;
  public int JJTDIV = 9;
  public int JJTNOT = 10;
  public int JJTNEGATE = 11;
  public int JJTPROPERTYCHAIN = 12;
  public int JJTCOMPUTEDPROPERTYCHAIN = 13;
  public int JJTIDENTIFIER = 14;
  public int JJTFUNCTION = 15;
  public int JJTINTEGER = 16;
  public int JJTSTRING = 17;
  public int JJTMAP = 18;
  public int JJTARRAY = 19;
  public int JJTMAPENTRY = 20;
  public int JJTFLOAT = 21;
  public int JJTBOOL = 22;
  public int JJTNULL = 23;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "LogicalOr",
    "LogicalAnd",
    "Equality",
    "Relational",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Not",
    "Negate",
    "PropertyChain",
    "ComputedPropertyChain",
    "Identifier",
    "Function",
    "Integer",
    "String",
    "Map",
    "Array",
    "MapEntry",
    "Float",
    "Bool",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=6ce368136a143bea0cbf0afe9b2bd767 (do not edit this line) */
