/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 6.0_1 */
package de.quinscape.exceed.expression;

public interface ExpressionParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTEXPRESSIONSEQUENCE = 2;
  public int JJTASSIGNMENT = 3;
  public int JJTLOGICALOR = 4;
  public int JJTLOGICALAND = 5;
  public int JJTEQUALITY = 6;
  public int JJTRELATIONAL = 7;
  public int JJTADD = 8;
  public int JJTSUB = 9;
  public int JJTMULT = 10;
  public int JJTDIV = 11;
  public int JJTNOT = 12;
  public int JJTNEGATE = 13;
  public int JJTPROPERTYCHAIN = 14;
  public int JJTPROPERTYCHAINDOT = 15;
  public int JJTPROPERTYCHAINSQUARE = 16;
  public int JJTIDENTIFIER = 17;
  public int JJTFUNCTION = 18;
  public int JJTINTEGER = 19;
  public int JJTSTRING = 20;
  public int JJTMAP = 21;
  public int JJTARRAY = 22;
  public int JJTMAPENTRY = 23;
  public int JJTDECIMAL = 24;
  public int JJTBOOL = 25;
  public int JJTNULL = 26;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "ExpressionSequence",
    "Assignment",
    "LogicalOr",
    "LogicalAnd",
    "Equality",
    "Relational",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "Not",
    "Negate",
    "PropertyChain",
    "PropertyChainDot",
    "PropertyChainSquare",
    "Identifier",
    "Function",
    "Integer",
    "String",
    "Map",
    "Array",
    "MapEntry",
    "Decimal",
    "Bool",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=95518e0efa99609ed4c6dd0581a45efd (do not edit this line) */
