/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 6.0_1 */
package de.quinscape.exceed.expression;

public interface ExpressionParserTreeConstants
{
  public int JJTEXPRESSION = 0;
  public int JJTVOID = 1;
  public int JJTLOGICALOR = 2;
  public int JJTLOGICALAND = 3;
  public int JJTEQUALITY = 4;
  public int JJTRELATIONAL = 5;
  public int JJTADD = 6;
  public int JJTSUB = 7;
  public int JJTMULT = 8;
  public int JJTDIV = 9;
  public int JJTPROPERTYCHAIN = 10;
  public int JJTIDENTIFIER = 11;
  public int JJTFUNCTION = 12;
  public int JJTINTEGER = 13;
  public int JJTSTRING = 14;
  public int JJTMAP = 15;
  public int JJTMAPENTRY = 16;
  public int JJTFLOAT = 17;
  public int JJTBOOL = 18;
  public int JJTNULL = 19;


  public String[] jjtNodeName = {
    "Expression",
    "void",
    "LogicalOr",
    "LogicalAnd",
    "Equality",
    "Relational",
    "Add",
    "Sub",
    "Mult",
    "Div",
    "PropertyChain",
    "Identifier",
    "Function",
    "Integer",
    "String",
    "Map",
    "MapEntry",
    "Float",
    "Bool",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=2db7e5c7b66221ad6384882a3374b54d (do not edit this line) */
