/* Generated By:JavaCC: Do not edit this line. ExpressionParserVisitor.java Version 6.0_1 */
package de.quinscape.exceed.expression;

public interface ExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTExpression node, Object data);
  public Object visit(ASTLogicalOr node, Object data);
  public Object visit(ASTLogicalAnd node, Object data);
  public Object visit(ASTEquality node, Object data);
  public Object visit(ASTRelational node, Object data);
  public Object visit(ASTAdd node, Object data);
  public Object visit(ASTSub node, Object data);
  public Object visit(ASTMult node, Object data);
  public Object visit(ASTDiv node, Object data);
  public Object visit(ASTPropertyChain node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTInteger node, Object data);
  public Object visit(ASTString node, Object data);
  public Object visit(ASTFloat node, Object data);
  public Object visit(ASTBool node, Object data);
  public Object visit(ASTNull node, Object data);
}
/* JavaCC - OriginalChecksum=f5f9f9abd4721ee12ae446228ca35073 (do not edit this line) */
