/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppState extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = -736223962;

	private String  id;
	private String  name;
	private String  path;
	private Integer status;
	private String  extensions;
	private String  context;
	private String  domainVersion;

	public AppState() {}

	public AppState(AppState value) {
		this.id = value.id;
		this.name = value.name;
		this.path = value.path;
		this.status = value.status;
		this.extensions = value.extensions;
		this.context = value.context;
		this.domainVersion = value.domainVersion;
	}

	public AppState(
		String  id,
		String  name,
		String  path,
		Integer status,
		String  extensions,
		String  context,
		String  domainVersion
	) {
		this.id = id;
		this.name = name;
		this.path = path;
		this.status = status;
		this.extensions = extensions;
		this.context = context;
		this.domainVersion = domainVersion;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@NotNull
	@Size(max = 255)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@NotNull
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Size(max = 255)
	public String getExtensions() {
		return this.extensions;
	}

	public void setExtensions(String extensions) {
		this.extensions = extensions;
	}

	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Size(max = 36)
	public String getDomainVersion() {
		return this.domainVersion;
	}

	public void setDomainVersion(String domainVersion) {
		this.domainVersion = domainVersion;
	}
}
