/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppTranslation extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = 2120134174;

	private String    id;
	private String    locale;
	private String    processName;
	private String    viewName;
	private String    tag;
	private String    translation;
	private Timestamp created;

	public AppTranslation() {}

	public AppTranslation(AppTranslation value) {
		this.id = value.id;
		this.locale = value.locale;
		this.processName = value.processName;
		this.viewName = value.viewName;
		this.tag = value.tag;
		this.translation = value.translation;
		this.created = value.created;
	}

	public AppTranslation(
		String    id,
		String    locale,
		String    processName,
		String    viewName,
		String    tag,
		String    translation,
		Timestamp created
	) {
		this.id = id;
		this.locale = locale;
		this.processName = processName;
		this.viewName = viewName;
		this.tag = tag;
		this.translation = translation;
		this.created = created;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 64)
	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String locale) {
		this.locale = locale;
	}

	@Size(max = 64)
	public String getProcessName() {
		return this.processName;
	}

	public void setProcessName(String processName) {
		this.processName = processName;
	}

	@Size(max = 64)
	public String getViewName() {
		return this.viewName;
	}

	public void setViewName(String viewName) {
		this.viewName = viewName;
	}

	@NotNull
	@Size(max = 255)
	public String getTag() {
		return this.tag;
	}

	public void setTag(String tag) {
		this.tag = tag;
	}

	@NotNull
	public String getTranslation() {
		return this.translation;
	}

	public void setTranslation(String translation) {
		this.translation = translation;
	}

	@NotNull
	public Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(Timestamp created) {
		this.created = created;
	}
}
