/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bar extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = 836741361;

	private String id;
	private String name;
	private String fooId;

	public Bar() {}

	public Bar(Bar value) {
		this.id = value.id;
		this.name = value.name;
		this.fooId = value.fooId;
	}

	public Bar(
		String id,
		String name,
		String fooId
	) {
		this.id = id;
		this.name = name;
		this.fooId = fooId;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Size(max = 36)
	public String getFooId() {
		return this.fooId;
	}

	public void setFooId(String fooId) {
		this.fooId = fooId;
	}
}
