/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables.pojos;


import de.quinscape.exceed.runtime.domain.GeneratedDomainObject;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.io.Serializable;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Foo extends GeneratedDomainObject implements Serializable {

	private static final long serialVersionUID = -571975027;

	private String    id;
	private String    name;
	private Integer   num;
	private Integer   type;
	private Timestamp created;
	private String    description;

	public Foo() {}

	public Foo(Foo value) {
		this.id = value.id;
		this.name = value.name;
		this.num = value.num;
		this.type = value.type;
		this.created = value.created;
		this.description = value.description;
	}

	public Foo(
		String    id,
		String    name,
		Integer   num,
		Integer   type,
		Timestamp created,
		String    description
	) {
		this.id = id;
		this.name = name;
		this.num = num;
		this.type = type;
		this.created = created;
		this.description = description;
	}

	@NotNull
	@Size(max = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@NotNull
	@Size(max = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@NotNull
	public Integer getNum() {
		return this.num;
	}

	public void setNum(Integer num) {
		this.num = num;
	}

	@NotNull
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@NotNull
	public Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(Timestamp created) {
		this.created = created;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
}
