/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables;


import de.quinscape.exceed.domain.Keys;
import de.quinscape.exceed.domain.Public;
import de.quinscape.exceed.domain.tables.records.AppTranslationRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppTranslation extends TableImpl<AppTranslationRecord> {

	private static final long serialVersionUID = 267875355;

	/**
	 * The reference instance of <code>public.app_translation</code>
	 */
	public static final AppTranslation APP_TRANSLATION = new AppTranslation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppTranslationRecord> getRecordType() {
		return AppTranslationRecord.class;
	}

	/**
	 * The column <code>public.app_translation.id</code>.
	 */
	public final TableField<AppTranslationRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(36).nullable(false), this, "");

	/**
	 * The column <code>public.app_translation.locale</code>.
	 */
	public final TableField<AppTranslationRecord, String> LOCALE = createField("locale", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>public.app_translation.tag</code>.
	 */
	public final TableField<AppTranslationRecord, String> TAG = createField("tag", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>public.app_translation.translation</code>.
	 */
	public final TableField<AppTranslationRecord, String> TRANSLATION = createField("translation", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * The column <code>public.app_translation.created</code>.
	 */
	public final TableField<AppTranslationRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.app_translation.process_name</code>.
	 */
	public final TableField<AppTranslationRecord, String> PROCESS_NAME = createField("process_name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * The column <code>public.app_translation.view_name</code>.
	 */
	public final TableField<AppTranslationRecord, String> VIEW_NAME = createField("view_name", org.jooq.impl.SQLDataType.VARCHAR.length(64), this, "");

	/**
	 * Create a <code>public.app_translation</code> table reference
	 */
	public AppTranslation() {
		this("app_translation", null);
	}

	/**
	 * Create an aliased <code>public.app_translation</code> table reference
	 */
	public AppTranslation(String alias) {
		this(alias, APP_TRANSLATION);
	}

	private AppTranslation(String alias, Table<AppTranslationRecord> aliased) {
		this(alias, aliased, null);
	}

	private AppTranslation(String alias, Table<AppTranslationRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AppTranslationRecord> getPrimaryKey() {
		return Keys.PK_APP_TRANSLATION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AppTranslationRecord>> getKeys() {
		return Arrays.<UniqueKey<AppTranslationRecord>>asList(Keys.PK_APP_TRANSLATION);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppTranslation as(String alias) {
		return new AppTranslation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AppTranslation rename(String name) {
		return new AppTranslation(name, null);
	}
}
