/**
 * This class is generated by jOOQ
 */
package de.quinscape.exceed.domain.tables;


import de.quinscape.exceed.domain.Keys;
import de.quinscape.exceed.domain.Public;
import de.quinscape.exceed.domain.tables.records.PersistentLoginsRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.6.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersistentLogins extends TableImpl<PersistentLoginsRecord> {

	private static final long serialVersionUID = -911953681;

	/**
	 * The reference instance of <code>public.persistent_logins</code>
	 */
	public static final PersistentLogins PERSISTENT_LOGINS = new PersistentLogins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PersistentLoginsRecord> getRecordType() {
		return PersistentLoginsRecord.class;
	}

	/**
	 * The column <code>public.persistent_logins.username</code>.
	 */
	public final TableField<PersistentLoginsRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>public.persistent_logins.series</code>.
	 */
	public final TableField<PersistentLoginsRecord, String> SERIES = createField("series", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>public.persistent_logins.token</code>.
	 */
	public final TableField<PersistentLoginsRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>public.persistent_logins.last_used</code>.
	 */
	public final TableField<PersistentLoginsRecord, Timestamp> LAST_USED = createField("last_used", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * Create a <code>public.persistent_logins</code> table reference
	 */
	public PersistentLogins() {
		this("persistent_logins", null);
	}

	/**
	 * Create an aliased <code>public.persistent_logins</code> table reference
	 */
	public PersistentLogins(String alias) {
		this(alias, PERSISTENT_LOGINS);
	}

	private PersistentLogins(String alias, Table<PersistentLoginsRecord> aliased) {
		this(alias, aliased, null);
	}

	private PersistentLogins(String alias, Table<PersistentLoginsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<PersistentLoginsRecord> getPrimaryKey() {
		return Keys.PERSISTENT_LOGINS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<PersistentLoginsRecord>> getKeys() {
		return Arrays.<UniqueKey<PersistentLoginsRecord>>asList(Keys.PERSISTENT_LOGINS_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersistentLogins as(String alias) {
		return new PersistentLogins(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PersistentLogins rename(String name) {
		return new PersistentLogins(name, null);
	}
}
